### PR TITLE
Add explanation of --gen3d option

### PR DESCRIPTION
**Pull request by n-yoshikawa**
This is related to openbabel/openbabel#1788.

The description is based on `openbabel/src/ops/gen3d.cpp`.

### CODE REVIEW

**Comment by baoilleach** [comment]
Great.

**Comment by baoilleach** [comment]
You can see the updated version now at https://open-babel.readthedocs.io/en/latest/Command-line_tools/babel.html#specify-speed

**Comment by laeeq80** [comment]
What is the default --gen3d use if we don't give any option? Maybe I missed it in the documentation.

**Comment by n-yoshikawa** [comment]
If we don't give any option, `med` is used because it is the default option.

I think the current explanation is enough, but if you have a good idea, please create a pull request.

**Pull request merged**
